config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

/*= Public routes
 *=====================================================*/
Router::scope('/', function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'pages', 'action' => 'home']);
    $routes->connect('/blog', ['controller' => 'posts', 'action' => 'index']);

    $routes->fallbacks(DashedRoute::class);
});

/*= Admin routes
 *=====================================================*/
Router::prefix('admin', function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'pages', 'action' => 'dashboard']);
    $routes->fallbacks('InflectedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/CoursesTable.php
<?php

namespace App\Model\Table;

use App\Model\Entity\Course;
use Cake\Datasource\EntityInterface;
use Cake\ORM\Association\BelongsTo;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Class CoursesTable
 *
 * @author Mathieu Bour <mathieu.tin.bour@gmail.com>
 * @package App\Model\Table
 *
 * @property BelongsTo $Users
 * @property BelongsTo $Levels
 * @property BelongsTo $Disciplines
 *
 * @method Course get($primaryKey, $options = [])
 * @method Course newEntity($data = null, array $options = [])
 * @method Course[] newEntities(array $data, array $options = [])
 * @method Course|bool save(EntityInterface $entity, $options = [])
 * @method Course patchEntity(EntityInterface $entity, array $data, array $options = [])
 * @method Course[] patchEntities($entities, array $data, array $options = [])
 * @method Course findOrCreate($search, callable $callback = null, $options = [])
 */
class CoursesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('courses');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        // Relations
        $this->belongsTo('Users');
        $this->belongsTo('Levels');
        $this->belongsTo('Disciplines');
    }

    /**
     * Default validation rules.
     *
     * @param Validator $validator Validator instance.
     * @return Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param RulesChecker $rules The rules object to be modified.
     * @return RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        $rules->add($rules->existsIn(['level_id'], 'Levels'));
        $rules->add($rules->existsIn(['discipline_id'], 'Disciplines'));

        return $rules;
    }
}

src/Model/Table/SlotsTable.php
<?php

namespace App\Model\Table;

use App\Model\Entity\Slot;
use Cake\Datasource\EntityInterface;
use Cake\ORM\Association\BelongsTo;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Class SlotsTable
 *
 * @author Mathieu Bour <mathieu.tin.bour@gmail.com>
 * @package App\Model\Table
 *
 * @property BelongsTo $Users
 *
 * @method Slot get($primaryKey, $options = [])
 * @method Slot newEntity($data = null, array $options = [])
 * @method Slot[] newEntities(array $data, array $options = [])
 * @method Slot|bool save(EntityInterface $entity, $options = [])
 * @method Slot patchEntity(EntityInterface $entity, array $data, array $options = [])
 * @method Slot[] patchEntities($entities, array $data, array $options = [])
 * @method Slot findOrCreate($search, callable $callback = null, $options = [])
 */
class SlotsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('slots');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Courses');
        $this->belongsTo('Levels');
        $this->belongsTo('Users');
    }

    /**
     * Default validation rules.
     *
     * @param Validator $validator Validator instance.
     * @return Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->integer('day')
            ->allowEmpty('day');

        $validator
            ->integer('hour')
            ->allowEmpty('hour');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param RulesChecker $rules The rules object to be modified.
     * @return RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));

        return $rules;
    }
}

src/Template/Admin/Pages/dashboard.ctp
<div class="row">
    <div class="col-md-3">
        <div class="panel bg-primary">
            <div class="panel-body">
                <div class="stat">
                    <div class="stat-number"><?= $stats['userCount']; ?></div>
                    <div class="stat-text">Utilisateurs inscrits</div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel bg-danger">
            <div class="panel-body">
                <div class="stat">
                    <div class="stat-number"><?= $stats['studentCount']; ?></div>
                    <div class="stat-text">Élèves inscrits</div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel bg-success">
            <div class="panel-body">
                <div class="stat">
                    <div class="stat-number"><?= $stats['teacherCount']; ?></div>
                    <div class="stat-text">Professeurs inscrits</div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel bg-warning">
            <div class="panel-body">
                <div class="stat">
                    <div class="stat-number"><?= (int)$stats['lessonsTotalDuration']; ?></div>
                    <div class="stat-text">Heures enseignées</div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h3>Inscriptions (semaine)</h3>
            </div>
            <div class="panel-body">
                <canvas id="user-registration-chart"></canvas>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h3>Cours donnés par date (semaine)</h3>
            </div>
            <div class="panel-body">
                <canvas id="lessons-given-by-date-chart"></canvas>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel">
            <div class="panel-heading">
                <h3>Détails des cours donnés (semaine)</h3>
            </div>
            <div class="panel-body">
                <canvas id="lessons-given-detail-chart"></canvas>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel">
            <div class="panel-heading">
                <h3>Matières les plus étudiés</h3>
            </div>
            <div class="panel-body">
                <canvas id="students-by-discipline-chart"></canvas>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel">
            <div class="panel-heading">
                <h3>Matières plus enseignées</h3>
            </div>
            <div class="panel-body">
                <canvas id="teachers-by-discipline-chart"></canvas>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h3>Professeurs les plus actifs</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Disciplines</th>
                                <th>Cours donnés</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($tables['bestTeachers'] as $teacher): ?>
                                <tr>
                                    <td><?= $teacher->lastname . ' ' . $teacher->firstname; ?></td>
                                    <td>
                                        <?php foreach ($teacher->courses as $course): ?>
                                            <span class="label label-primary">
                                            <?= $course->discipline->name . ' (' . $course->level->name . ')'; ?>
                                        </span>&nbsp;
                                        <?php endforeach; ?>
                                    </td>
                                    <td><?= $teacher->lesson_count; ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h3>Élèves les plus actifs</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Disciplines</th>
                                <th>Cours suivis</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($tables['bestStudents'] as $student): ?>
                                <tr>
                                    <td><?= $student->lastname . ' ' . $student->firstname; ?></td>
                                    <td>
                                        <?php foreach ($student->courses as $course): ?>
                                            <span class="label label-primary">
                                            <?= $course->discipline->name . ' (' . $course->level->name . ')'; ?>
                                        </span>&nbsp;
                                        <?php endforeach; ?>
                                    </td>
                                    <td><?= $student->lesson_count; ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->start('script'); ?>
<script>
    new Chart($('#user-registration-chart'), <?= json_encode($charts['userRegistration']); ?>);
    new Chart($('#lessons-given-by-date-chart'), <?= json_encode($charts['lessonsGivenByDate']); ?>);
    new Chart($('#lessons-given-detail-chart'), <?= json_encode($charts['lessonsGivenDetail']); ?>);
    new Chart($('#students-by-discipline-chart'), <?= json_encode($charts['studentsByDisciplineChart']); ?>);
    new Chart($('#teachers-by-discipline-chart'), <?= json_encode($charts['teachersByDisciplineChart']); ?>);
</script>
<?php $this->end(); ?>

src/Template/Admin/Pages/settings.ctp
<div class="row">
    <div class="col-md-3">
        <div class="panel">
            <div class="panel-heading">
                <h3>Niveaux scolaires</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nom</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($levels as $level): ?>
                            <tr>
                                <td><?= $level->name; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel">
            <div class="panel-heading">
                <h3>Ajouter un niveau</h3>
            </div>
            <div class="panel-body">
                <?= $this->Form->create(null, ['url' => ['controller' => 'levels', 'action' => 'add']]); ?>
                <?= $this->Form->input('name', [
                    'label' => 'Nom du niveau'
                ]); ?>
                <?= $this->Form->end(); ?>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel">
            <div class="panel-heading">
                <h3>Disciplines scolaires</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nom</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($disciplines as $discipline): ?>
                            <tr>
                                <td><?= $discipline->name; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel">
            <div class="panel-heading">
                <h3>Ajouter une discipline</h3>
            </div>
            <div class="panel-body">
                <?= $this->Form->create(null, ['url' => ['controller' => 'disciplines', 'action' => 'add']]); ?>
                <?= $this->Form->input('name', [
                    'label' => 'Nom de la discipline'
                ]); ?>
                <?= $this->Form->end(); ?>
            </div>
        </div>
    </div>
</div>